---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 54125c7d291289aaea51ca313fc694d057d803fa
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 73d16a19970db4d1e27aa284bc3e4786b8a3c659
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 87f4498f90f0cbb66a1ddb425e8953b04ced1891
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git
