---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: d72a2ce8d1926f24bdde0bdd951fbcfcdacbb991
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 7243d806a6f7a6504ba6a775e013c14956e0e334
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 87f4498f90f0cbb66a1ddb425e8953b04ced1891
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git
