---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 54125c7d291289aaea51ca313fc694d057d803fa
  scm: git

- name: infra-role-bootstrap
  src: git@github.com:status-im/infra-role-bootstrap.git
  version: efd7dd1f249bc4cb4f9dcc9ee2ff4ce04f9ac3bd
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: b1d5ad5caa7d7a036fd175292fa497175bb7c54c
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git
